### ISSUE TITLE
Update dependencies and add badges

### ISSUE THREAD

**Issue by jared-stilwell** [jared-stilwell/escomplex-js#3]
Update the dependencies and dev-dependencies based on the [david-dm status](https://david-dm.org/jared-stilwell/escomplex-js).

Add badges for the dependencies (http://david-dm.org/jared-stilwell/escomplex-js.svg) and dev-dependencies (http://david-dm.org/jared-stilwell/escomplex-js/dev-status.svg).

**Comment by ludovicofischer** [comment]
If you want I can submit pull requests for the open issues, in the interest of getting ES6 support (see https://github.com/es-analysis/plato/issues/127)
